services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file: .env
    ports:
      - "5050:80"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${PG_DB}
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: ${PG_PASS}
      MYSQL_PORT: "3306"
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${PG_PASS}
      PMA_HOST: mysql
    env_file: .env
    ports:
      - "8080:80"


